services:
  postgres:
    image: postgres:16-alpine
    container_name: gestopago-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: gestopago_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d gestopago_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:7.0
    container_name: gestopago-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
    name: gestopago_postgres_data
  mongo_data:
    name: gestopago_mongo_data
