# Servidor
server.port=8081

# Base de datos PostgreSQL
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/gestopago_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# Flyway Migraciones
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.schemas=public
spring.flyway.table=flyway_schema_history

# Integración GestoPago Autenticación
gestopago.auth.url=${GESTOPAGO_AUTH_URL:https://gestopago.portalventas.net}
gestopago.auth.id-distribuidor=${GESTOPAGO_ID_DISTRIBUIDOR:83}
gestopago.auth.codigo-dispositivo=${GESTOPAGO_CODIGO_DISPOSITIVO:GPS83-TPV-17}
gestopago.auth.password=${GESTOPAGO_PASSWORD:12345678}
gestopago.auth.refresh-rate-ms=3600000

# Integración GestoPago Catálogo de Productos
gestopago.catalogo.url=${GESTOPAGO_CATALOGO_URL:https://gestopago.portalventas.net}
gestopago.catalogo.cron=${GESTOPAGO_CATALOGO_CRON:0 0 6 * * *}

# Configuración MongoDB para Catálogo de Productos
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/gestopago_catalogo}
